#!/bin/bash
# dev-squad: Stop hook — full verification gate
# Inspired by iamfakeguru/claude-md stop-verify.sh
# Runs tsc + lint + tests before agent can claim "done"
# Only activates when project files exist (not in empty dirs)

# Infinite-loop protection: if stop_hook_active is set, let through
HOOK_INPUT=$(cat - 2>/dev/null || echo "{}")
STOP_HOOK_ACTIVE=$(echo "$HOOK_INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('stop_hook_active', False))" 2>/dev/null || echo "False")

if [ "$STOP_HOOK_ACTIVE" = "True" ]; then
  exit 0
fi

# Skip if no dev-squad workflow active
if [ ! -f ".dev-squad/workflow-active" ]; then
  exit 0
fi

# Read mode once here so both the no-project-files guard and the auto-mode block below share it
AUTO_MODE=$(python3 -c "import json,sys; print(json.load(open(sys.argv[1])).get('mode',''))" ".dev-squad/workflow-active" 2>/dev/null)

# Skip if no project files detected (not in a project directory)
# In auto mode, no project files means scaffold never ran — treat as floor-miss
if [ ! -f "tsconfig.json" ] && [ ! -f "package.json" ] && [ ! -f "go.mod" ] && [ ! -f "pyproject.toml" ] && [ ! -f "setup.py" ] && [ ! -f "Cargo.toml" ]; then
  if [ "$AUTO_MODE" = "auto" ]; then
    {
      echo "# Auto-mode run did NOT meet the quality floor"
      echo ""
      echo "Generated by stop-verify.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
      echo ""
      echo "## Reasons"
      echo "run reached Stop before producing any project files (scaffold incomplete); "
      echo ""
      echo "## Next steps"
      echo "- Review .dev-squad/assumption-ledger.md for inferred decisions (especially LOW confidence)."
      echo "- This run is NOT shippable. Human review required before merge."
    } > ".dev-squad/auto-failure-report.md"
    echo "STOP BLOCKED — auto-mode quality floor not met: run reached Stop before producing project files. See .dev-squad/auto-failure-report.md."
    exit 2
  fi
  exit 0
fi

ERRORS=""

# v4.15.3: per-command timeout to prevent full Stop hook (300s) being consumed by
# a single slow tsc/eslint/test invocation in a large monorepo.
PER_CMD_TIMEOUT=90

run_timed() {
  if command -v timeout >/dev/null 2>&1; then
    timeout "$PER_CMD_TIMEOUT" "$@"
  elif command -v gtimeout >/dev/null 2>&1; then
    gtimeout "$PER_CMD_TIMEOUT" "$@"
  else
    "$@"
  fi
}

# Detect project type and run verification
if [ -f "tsconfig.json" ] || [ -f "package.json" ]; then
  # TypeScript/JavaScript project

  # 1. Type check
  if [ -f "tsconfig.json" ] && command -v npx &>/dev/null; then
    TSC_OUTPUT=$(run_timed npx tsc --noEmit 2>&1)
    rc=$?
    if [ $rc -eq 124 ]; then
      ERRORS="${ERRORS}TypeScript: tsc timed out (${PER_CMD_TIMEOUT}s). "
    elif [ $rc -ne 0 ]; then
      ERROR_COUNT=$(echo "$TSC_OUTPUT" | grep -c "error TS")
      ERRORS="${ERRORS}TypeScript: ${ERROR_COUNT} type errors. "
    fi
  fi

  # 2. Lint
  if [ -f "node_modules/.bin/eslint" ]; then
    LINT_OUTPUT=$(run_timed npx eslint . --quiet 2>&1)
    rc=$?
    if [ $rc -eq 124 ]; then
      ERRORS="${ERRORS}ESLint: timed out (${PER_CMD_TIMEOUT}s). "
    elif [ $rc -ne 0 ]; then
      LINT_COUNT=$(echo "$LINT_OUTPUT" | grep -c "error")
      ERRORS="${ERRORS}ESLint: ${LINT_COUNT} errors. "
    fi
  fi

  # 3. Tests
  if [ -f "package.json" ] && grep -q '"test"' package.json 2>/dev/null; then
    TEST_OUTPUT=$(run_timed npm test --silent 2>&1)
    rc=$?
    if [ $rc -eq 124 ]; then
      ERRORS="${ERRORS}Tests: timed out (${PER_CMD_TIMEOUT}s). "
    elif [ $rc -ne 0 ]; then
      ERRORS="${ERRORS}Tests: failing. "
    fi
  fi

elif [ -f "go.mod" ]; then
  # Go project

  # 1. Build check
  BUILD_OUTPUT=$(run_timed go build ./... 2>&1)
  rc=$?
  if [ $rc -eq 124 ]; then
    ERRORS="${ERRORS}Go build: timed out. "
  elif [ $rc -ne 0 ]; then
    ERRORS="${ERRORS}Go build: failed. "
  fi

  # 2. Vet
  VET_OUTPUT=$(run_timed go vet ./... 2>&1)
  rc=$?
  if [ $rc -eq 124 ]; then
    ERRORS="${ERRORS}Go vet: timed out. "
  elif [ $rc -ne 0 ]; then
    ERRORS="${ERRORS}Go vet: issues found. "
  fi

  # 3. Tests
  TEST_OUTPUT=$(run_timed go test ./... 2>&1)
  rc=$?
  if [ $rc -eq 124 ]; then
    ERRORS="${ERRORS}Go tests: timed out. "
  elif [ $rc -ne 0 ]; then
    ERRORS="${ERRORS}Go tests: failing. "
  fi

elif [ -f "pyproject.toml" ] || [ -f "setup.py" ]; then
  # Python project

  # 1. Type check
  if command -v mypy &>/dev/null; then
    MYPY_OUTPUT=$(run_timed mypy . 2>&1)
    rc=$?
    if [ $rc -eq 124 ]; then
      ERRORS="${ERRORS}mypy: timed out. "
    elif [ $rc -ne 0 ]; then
      ERRORS="${ERRORS}mypy: type errors. "
    fi
  fi

  # 2. Lint
  if command -v ruff &>/dev/null; then
    RUFF_OUTPUT=$(run_timed ruff check . 2>&1)
    rc=$?
    if [ $rc -eq 124 ]; then
      ERRORS="${ERRORS}ruff: timed out. "
    elif [ $rc -ne 0 ]; then
      ERRORS="${ERRORS}ruff: lint errors. "
    fi
  fi

  # 3. Tests
  if command -v pytest &>/dev/null; then
    TEST_OUTPUT=$(run_timed pytest --quiet 2>&1)
    rc=$?
    if [ $rc -eq 124 ]; then
      ERRORS="${ERRORS}pytest: timed out. "
    elif [ $rc -ne 0 ]; then
      ERRORS="${ERRORS}pytest: failing. "
    fi
  fi
fi

# --- SP1 auto-mode termination contract (runs before the interactive exit) ---
if [ "$AUTO_MODE" = "auto" ]; then
  FLOOR_FAIL=""
  [ -n "$ERRORS" ] && FLOOR_FAIL="${FLOOR_FAIL}verification failed: ${ERRORS}; "

  if [ -f ".dev-squad/iteration-log.md" ] && grep -qiE 'UNRESOLVED (P0|P1)|escalate to user' ".dev-squad/iteration-log.md"; then
    FLOOR_FAIL="${FLOOR_FAIL}unresolved P0/P1 findings; "
  fi

  # Deterministic phase-completeness floor. The iteration-log check above is a PROSE handoff:
  # coordinator.md:739 says a failed gate must write 'UNRESOLVED P1' to iteration-log.md so this
  # hook picks it up — but if the agent forgets that line, the gate silently passes (fail-open).
  # A failed gate is told "Do NOT pass" (coordinator.md:739), so the phase it was working stays
  # 'in_progress'; reading that status directly catches the miss without the prose marker.
  # Flag ONLY 'in_progress' — that is unambiguously "started but not finished". Do NOT flag
  # 'pending': the status vocabulary is pending/in_progress/complete only (coordinator.md:534) —
  # there is no 'skipped' status, so a legitimately skipped phase (e.g. ui_design when
  # feature.has_ui==false, zero-to-ship.json) is left 'pending', and flagging it would wrongly
  # block a valid backend-only auto run.
  WF_CONTENT=$(cat ".dev-squad/workflow-active" 2>/dev/null)
  INPROGRESS_PHASES=""
  for phase in ultraplan discover design scaffold ui_design implement review ship learn; do
    st=$(printf '%s' "$WF_CONTENT" | grep -o "\"$phase\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" | grep -o '"[^"]*"$' | tr -d '"')
    if [ "$st" = "in_progress" ]; then
      INPROGRESS_PHASES="${INPROGRESS_PHASES}${phase} "
    fi
  done
  [ -n "$INPROGRESS_PHASES" ] && FLOOR_FAIL="${FLOOR_FAIL}phase still in_progress at stop: ${INPROGRESS_PHASES}; "

  if [ -f ".dev-squad/auto-run.json" ] && python3 -c "import json,sys; sys.exit(0 if json.load(open('.dev-squad/auto-run.json')).get('halted') else 1)" 2>/dev/null; then
    HALT_REASON=$(python3 -c "import json; print(json.load(open('.dev-squad/auto-run.json')).get('halt_reason') or 'budget exceeded')" 2>/dev/null)
    FLOOR_FAIL="${FLOOR_FAIL}governor halted run (${HALT_REASON}); "
  fi

  if [ -n "$FLOOR_FAIL" ]; then
    {
      echo "# Auto-mode run did NOT meet the quality floor"
      echo ""
      echo "Generated by stop-verify.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
      echo ""
      echo "## Reasons"
      echo "${FLOOR_FAIL}"
      echo ""
      echo "## Next steps"
      echo "- Review .dev-squad/assumption-ledger.md for inferred decisions (especially LOW confidence)."
      echo "- This run is NOT shippable. Human review required before merge."
    } > ".dev-squad/auto-failure-report.md"
    echo "STOP BLOCKED — auto-mode quality floor not met: ${FLOOR_FAIL}See .dev-squad/auto-failure-report.md."
    exit 2
  fi
  # floor met -> fall through to clean exit below
fi
# --- end auto-mode block ---

# If no verification errors, allow stop
if [ -z "$ERRORS" ]; then
  exit 0
fi

# Block stop with errors (interactive path)
echo "STOP BLOCKED — verification failed: ${ERRORS}Fix all errors before claiming done."
exit 2
